### ISSUE TITLE
Make abstract component.

### ISSUE THREAD

**Issue by tarao1006** [tarao1006/numerical-calculation#2]
# Summary
There are three similar components. Make an abstract class and they should be its composition.

# TODO
- [ ] Create abstract container component.
- [ ] Delete `decompositioncontainer.jsx`.
- [ ] Delete `substitutioncontainer.jsx`.
