### ISSUE TITLE
Add header component.

### ISSUE THREAD

**Issue by tarao1006** [tarao1006/numerical-calculation#5]
# Summary
Add some static pages like "about" and add header component to link them.

# TODO
- [ ] Check famous web page to design heade component.
- [ ] Add about page.
- [ ] Add header component.
